### PR TITLE
32341 text wrap

### PR DESCRIPTION
**Pull request by dletorey**
### Description

Added interactive examples for:
- text-wrap-style
- text-wrap-mode

### Motivation

Working on the [Convert text-wrap CSS property to a shorthand](https://github.com/mdn/content/issues/32341) Issue

### Related issues and pull requests
- [Content PR](https://github.com/mdn/content/pull/32728)
- [BCD PR](https://github.com/mdn/browser-compat-data/pull/22621)
- [Firefox Release note PR](https://github.com/mdn/content/pull/32729)
- [data PR](https://github.com/mdn/data/pull/720)

### CODE REVIEW

**Comment by dipikabh** [comment]
Hi @dletorey, thanks for the PR!

I started looking at this, but I didn't find the examples in my local preview at this path "http://127.0.0.1:9090/pages/css/".

I am wondering if you also need to do this step, [Updating the metadata](https://github.com/mdn/interactive-examples/blob/main/contributing/css-examples.md#updating-the-metadata), so that the examples get added to the page generator.
So you'd have two entries in this `live-examples/css-examples/text/meta.json` file for the two new examples.

**Comment by dletorey** [comment]
> Hi @dletorey, thanks for the PR!
> 
> I started looking at this, but I didn't find the examples in my local preview at this path "http://127.0.0.1:9090/pages/css/".
> 
> I am wondering if you also need to do this step, [Updating the metadata](https://github.com/mdn/interactive-examples/blob/main/contributing/css-examples.md#updating-the-metadata), so that the examples get added to the page generator. So you'd have two entries in this `live-examples/css-examples/text/meta.json` file for the two new examples.

I have now added this and yes you are correct.
These 2 urls now work for me, but only in nightly/beta:
- [http://127.0.0.1:9090/pages/css/text-wrap-mode.html](http://127.0.0.1:9090/pages/css/text-wrap-mode.html)
- [http://127.0.0.1:9090/pages/css/text-wrap-style.html](http://127.0.0.1:9090/pages/css/text-wrap-style.html)

**Comment by dipikabh** [comment]
Thanks, @dletorey, that fixed it.

Yes, based on your BCD PR, I'm testing this in Firefox 124.0b9.

- `text-wrap-mode` is looking good ✅ 
- `text-wrap-style`: The `pretty` option does not seem to be recognized.

<kbd>interactive example screenshot</kbd>

The style inspector also does not show `pretty` as one of the options for `text-wrap-style`:

<kbd>screenshot of style inspector</kbd>

**Comment by dletorey** [comment]
> Thanks, @dletorey, that fixed it.
> 
> Yes, based on your BCD PR, I'm testing this in Firefox 124.0b9.
> 
>     * `text-wrap-mode` is looking good ✅
> 
>     * `text-wrap-style`: The `pretty` option does not seem to be recognized.
> 
> 
> interactive example screenshot
> 
> The style inspector also does not show `pretty` as one of the options for `text-wrap-style`:
> 
> screenshot of style inspector

Hi @dipikabh 

This is purely due to `pretty` not yet being supported in Firefox, `text-wrap-style` is currently only supported in Firefox but further down the line it will be.

`text-wrap: pretty;` is supported in most chromium based browsers

**Comment by dipikabh** [comment]
Got it!

In that case, might be a good idea to make `text-wrap-style` BCD also show support per value, similar to the BCD for [`text-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#browser_compatibility). Because readers will naturally scroll down to the BCD section after they see the yellow cross.

**Review by dipikabh — APPROVED** [review]
Thanks for adding these examples, @dletorey!

**Pull request merged**
