### PR TITLE
Update interactive examples for comparison operators

### PR DESCRIPTION
**Pull request by yurj26**

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
That doesn't seem like a good change. The [strict inequality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_inequality) page shows the behavior of `!==`, so what's the reasoning of changing this example?

**Comment by yurj26** [comment]
see https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Strict_inequality

**Comment by NiedziolkaMichal** [comment]
It's a problem with the content repository. Could you go to [strict_inequality](https://github.com/mdn/translated-content/edit/main/files/zh-cn/web/javascript/reference/operators/strict_inequality/index.md) and replace `{{EmbedInteractiveExample("pages/js/expressions-strict-equality.html")}}` with `{{EmbedInteractiveExample("pages/js/expressions-strict-inequality.html")}}`?

**Comment by yurj26** [comment]
ok, thanks, I misread it.

**Comment by NiedziolkaMichal** [comment]
That's ok, I will close this one.

**Pull request closed without merging**
