### PR TITLE
Unprefixed `appearance` is now standardized

### PR DESCRIPTION
**Pull request by jmswisher**
Refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1620467 and the recently-updated [appearance](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/appearance) reference article.

### CODE REVIEW

**Review by velusgautam — APPROVED** [review]

**Comment by velusgautam** [comment]
Nice work @jmswisher.

**Comment by jmswisher** [comment]
@chrisdavidmills @ddbeck Is this OK to merge?

**Review by ddbeck — APPROVED** [review]
@jmswisher This looks fine to me, but I don't actually have merge privileges on this repo.

**Comment by peterbe** [comment]
Hi friends, @schalkneethling will take care of this but he's been having some recent connectivity issues so a bit backed up.

**Pull request merged**
