### PR TITLE
feat(ci): run all linting actions

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates the GitHub Action to test a PR to ensure it also checks Prettier formatting.

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
LGTM 👍🏻

**Review by bsmth — CHANGES_REQUESTED** [review]
oops, missed the failing CI, what's the issue here?

**Comment by bsmth** [comment]
> oops, missed the failing CI, what's the issue here?

Copying from the logs:

```
Error:  live-examples/html-examples/inline-text-semantics/rtc.html: SyntaxError: Unexpected closing tag "rtc". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (10:5)
Error:     8 |     <rtc xml:lang="en" style="ruby-position: over;">
Error:     9 |         <rp>(</rp><rt>Malaysia</rt><rp>)</rp>
Error:  > 10 |     </rtc>
Error:       |     ^^^^^^
Error:    11 | </ruby>
Error:    12 |
```

**Comment by queengooborg** [comment]
Looks like bad formatting in a file.  We should probably fix that and then merge this immediately after to prevent regressions in the future.

**Comment by bsmth** [comment]
There's an [implied closing tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rtc#technical_summary) ([spec](https://html.spec.whatwg.org/multipage/parsing.html#closing-elements-that-have-implied-end-tags)) so Prettier is okay with this:

```html
<ruby xml:lang="zh-Hant" style="ruby-position: under">
  <rbc>
    <rb>馬</rb><rp>(</rp><rt>mǎ</rt><rp>)</rp> <rb>來</rb><rp>(</rp><rt>lái</rt><rp>)</rp> <rb>西</rb><rp>(</rp
    ><rt>xī</rt><rp>)</rp> <rb>亞</rb><rp>(</rp><rt>yà</rt><rp>)</rp>
  </rbc>
  <rtc xml:lang="en" style="ruby-position: over"> </rtc><rp>(</rp><rt>Malaysia</rt><rp>)</rp>
</ruby>
```

But it looks pretty gnarly compared to [the original](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rtc#try_it):

```html
<ruby xml:lang="zh-Hant" style="ruby-position: under;">
    <rbc>
        <rb>馬</rb><rp>(</rp><rt>mǎ</rt><rp>)</rp>
        <rb>來</rb><rp>(</rp><rt>lái</rt><rp>)</rp>
        <rb>西</rb><rp>(</rp><rt>xī</rt><rp>)</rp>
        <rb>亞</rb><rp>(</rp><rt>yà</rt><rp>)</rp>
    </rbc>
    <rtc xml:lang="en" style="ruby-position: over;">
        <rp>(</rp><rt>Malaysia</rt><rp>)</rp>
    </rtc>
</ruby>
```

**Comment by bsmth** [comment]
This depends on the linked PR:

- [x] https://github.com/mdn/interactive-examples/pull/2592

**Review by caugner — APPROVED** [review]

**Comment by caugner** [comment]
Thank you @queengooborg! 🎉

**Pull request merged**
