### PR TITLE
 Add object-keys.html

### PR DESCRIPTION
**Pull request by elharony**
The code is the same as `object-values.html` the only difference is that here we are printing out the `keys`, not the `values`.

_P.S: This is my first Pull Request, but I am going to constantly improve MDN Web Docs pages!_

### CODE REVIEW

**Comment by schalkneethling** [comment]
@elharony Thanks so much for your contribution. There are still a couple of items missing from this pull request. Please have a look at the contribution guidelines for JavaScript examples for all the details:

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING.md#contributing-a-javascript-example

Please let me know if anything is unclear.

**Comment by schalkneethling** [comment]
@elharony Doh! I should have pointed you at the JS specific guide. One thing that is missing is the metadata info:
https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-JavaScript.md#updating-the-metadata

And then also the testing potion:
https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING.md#testing

Thanks again for your contribution.

**Comment by schalkneethling** [comment]
@elharony You need the following entry:

```
"objectKeys": {
    "baseTmpl": "tmpl/live-js-tmpl.html",
    "exampleCode": "live-examples/js-examples/object/object-keys.html",
    "fileName": "object-keys.html",
    "title": "JavaScript Demo: Object.keys()",
    "type": "js"
}
```

in the `meta.json` here:
https://github.com/mdn/interactive-examples/blob/master/live-examples/js-examples/object/meta.json at around line 114

With that added, this will be good to merge. Thanks!

**Comment by elharony** [comment]
Thanks @schalkneethling !

I've created a new `Pull Request` with the required changes. Thank you for your explanation! 👍

**Comment by schalkneethling** [comment]
Closing in favour of https://github.com/mdn/interactive-examples/pull/937

**Pull request closed without merging**
