### PR TITLE
Contrast in transform-style

### LINKED ISSUE #2054: Improve contrast of interactive example
There are probably other situations where too little contrast makes things hard to see. Compare these white letters on bright yellow background atop this page,

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

I'll stop reporting these, anyone could find them easily.

_Originally posted by @iDave2 in https://github.com/mdn/yari/issues/5387#issuecomment-1055782535_

### PR DESCRIPTION
**Pull request by rohini-ranjanR**
### Description
I change the color and background color in transform style to have a good contrast

### Related issues and pull requests
#2054

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
Thank you for this contribution. I have commented on two small things that I think could be improved. Feel free to disagree.
Could you also add `alt=""` to `transform-origin.html`? Validator is showing a warning about the missing tag.

**Comment by rohini-ranjanR** [comment]
Yeah sure

**Comment by NiedziolkaMichal** [comment]
Thank you. I have also removed `Fixes ` word from your first comment because merging the PR would close the issue entirely, while many other changes are required.

**Comment by NiedziolkaMichal** [comment]
I will close it as a duplicate of #2419. Next time please add changes to the existing pull request, instead of creating a new one.

**Pull request closed without merging**
