### PR TITLE
Added await to the wasm instantiate calls

### PR DESCRIPTION
**Pull request by MendyBerger**
Needed to display runtime errors mdn/bob/pull/697

### CODE REVIEW

**Comment by MendyBerger** [comment]
@sideshowbarker anything I can do to speed up the review process for this pr?

**Comment by sideshowbarker** [comment]
> @sideshowbarker anything I can do to speed up the review process for this pr?

Can you suggest a reviewer? There’s no reviewer assigned, so it’s possible that nobody has even noticed it

**Comment by MendyBerger** [comment]
Not sure, maybe @schalkneethling (since he merged the related pr)

Is there a list of people that are qualified to review PRs?

**Comment by sideshowbarker** [comment]
> Is there a list of people that are qualified to review PRs?

I don’t think the list of people with merge perms is exposed, but otherwise anybody at all can review and comment here.

What I had in mind is that in general, for any given PR, it’s best to have someone with domain knowledge about it do a technical review, and then ask somebody with merge perms to merge it.

But anyway, this is one straightforward enough that I’ll just go ahead and merge it

**Review by sideshowbarker — APPROVED** [review]

**Comment by MendyBerger** [comment]
I might have someone with lots of wasm knowledge, let's see if they'd be willing to do reviews of these things

**Comment by MendyBerger** [comment]
The one and only @sunfishcode agreed to do reviews on my wasm PRs! I'll tag him on future PRs

**Comment by sideshowbarker** [comment]
> The one and only @sunfishcode agreed to do reviews on my wasm PRs! I'll tag him on future PRs

🎉 Excellent

**Pull request merged**
