### PR TITLE
chore: use github actions to deploy

### LINKED ISSUE #1893: Switch to GitHub Actions
To consolidate how we build and release projects, we should switch this repo to using GitHub actions as well

### PR DESCRIPTION
**Pull request by schalkneethling**
Use GitHub Actions to deploy pages.

@escattone I _think_ this will do the trick. I guess the only way to test is to merge and then see what happens?

fix #1893

### CODE REVIEW

**Review by escattone — CHANGES_REQUESTED** [review]

**Comment by schalkneethling** [comment]
Commited your suggestions. Thank you for the input @escattone

**Review by escattone — CHANGES_REQUESTED** [review]
@schalkneethling One more thing. Instead of renaming `travis-deploy-pages` → `.github/workflows/travis-deploy-pages`, that file should be deleted since it's no longer used.

**Comment by schalkneethling** [comment]
> @schalkneethling One more thing. Instead of renaming `travis-deploy-pages` → `.github/workflows/travis-deploy-pages`, that file should be deleted since it's no longer used.

Doh!

**Review by escattone — APPROVED** [review]
Thanks @schalkneethling!

**Pull request merged**
