### PR TITLE
Add demo for text-decoration-skip-ink

### PR DESCRIPTION
**Pull request by paulirish**
image

### CODE REVIEW

**Comment by paulirish** [comment]
awesome, thanks!

 when can i add `<div>{{EmbedInteractiveExample("pages/css/text-decoration-skip-ink.html")}}</div>` to https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink ?

I just got this error:
image

presumably gotta wait for some push.. like a few hours or a ~day? thx

**Comment by wbamberg** [comment]
It should be deployed to https://interactive-examples.mdn.mozilla.net/pages/css/text-decoration-skip-ink.html (cf https://interactive-examples.mdn.mozilla.net/pages/css/text-decoration.html), pretty soon I think, although I'm not familiar with how that magic happens.

After that we will be able to include it in pages.

**Comment by wbamberg** [comment]
Oh, it's up now: https://interactive-examples.mdn.mozilla.net/pages/css/text-decoration-skip-ink.html :)

**Comment by paulirish** [comment]
cool! 

hmmmm. the `hidden` class is set on a bunch of it. 
compare https://interactive-examples.mdn.mozilla.net/pages/css/text-decoration.html to https://interactive-examples.mdn.mozilla.net/pages/css/text-decoration-skip-ink.html 

do you know what's up with that?

**Comment by wbamberg** [comment]
I'm not sure what you mean. I see this in Chrome:

skip-ink-chrome

 ... and this in Firefox:

skip-ink-firefox

This is what I would expect - the editor does feature detection and hides the interactive bits when the browser doesn't support the property - which Firefox doesn't, in this case.

Is this not what you see, or not what you expected to see?

**Comment by paulirish** [comment]
Ah cool! Ok I must have been looking at it in chrome 63. :) Cool!

**Pull request merged**
