### PR TITLE
Update Intl.DateTimeFormat to show options in constructor

### PR DESCRIPTION
**Pull request by hamishwillee**
Previous example just shows default formatting based on locale, and locale with language fallback. This extends the example just a little to show how the date can be formatted using style and custom options.

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Hi @hamishwillee !

This is looking pretty good. I just had a coupleof issues here:

1. Generally we try to keep interactive examples to about 13 lines long at a maximum, otherwise they don't fit very well in the context of the rest of the page. Can you try to cut this down a bit?

2. You've got some CI failures to pick through and fix, mainly just stylistic stuff.

**Comment by hamishwillee** [comment]
@chrisdavidmills This was already thirteen lines before I started, and showed only a fraction of what this can do :-(. I deleted a few interesting options and got it down to 14. If that is too many we might as well just just close this an accept we can't do a good job.

**Comment by chrisdavidmills** [comment]
This looks much better! You still have a CI error, but nearly there.

**Comment by hamishwillee** [comment]
Fixed, I hope! Travis running a bit slow.

**Review by chrisdavidmills — APPROVED** [review]
Much better, thanks!

**Pull request merged**
