### PR TITLE
Fix issue #450, wrap calls to localStorage in try/catch

### PR DESCRIPTION
**Pull request by schalkneethling**

### CODE REVIEW

**Comment by wbamberg** [comment]
This looks fine, but is there any way I can test it?

I don't really understand how changing cookie settings can stop local storage from working.

**Comment by schalkneethling** [comment]
> I don't really understand how changing cookie settings can stop local storage from working.

It is odd, but that is what @kenrick95 was seeing. Perhaps he can give this a go and see if it resolved the problem. @kenrick95 ?

**Comment by wbamberg** [comment]
I can see the problem @kenrick95 reported on [prod](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter), if I change my cookie settings as per his comment: https://github.com/mdn/interactive-examples/issues/450#issuecomment-360319631.

In Chrome, I get a better error message:

> Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

...which definitely points to localStorage.

But I can't reproduce the problem locally, so I can't test whether this fixes the problem :(.

**Comment by schalkneethling** [comment]
> Maybe it would be simpler just to merge it and test afterwards :).

I am thinking that. I believe it will still fail but, at least now it will write a custom message to the console and not the error from the browser.

**Comment by wbamberg** [comment]
I can confirm that this has the expected result :). With third party cookies off:

screen shot 2018-01-31 at 2 11 56 pm

**Pull request merged**
