### PR TITLE
added path() example to basic shapes (CSS values)

### PR DESCRIPTION
**Pull request by estelle**
Adding path() as a basic shape.
It is not supported in clip-path. (but it is supported in offset-path in FF63, with motion path in Chrome)

specs: 
Definition of path()
https://drafts.csswg.org/css-shapes-2/#supported-basic-shapes

to be added to basic shapes at:
https://www.w3.org/TR/css-shapes/#basic-shape-functions

as per bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1246764

### CODE REVIEW

**Comment by wbamberg** [comment]
I'm not sure I understand the situation here. In https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path#Browser_compatibility it doesn't say that `clip-path: path(...)` is not supported, but it doesn't seem to work in this example and your comment:

> It is not supported in clip-path. 

obviously indicates that it isn't.

I don't think we should include options in the interactive examples that don't work yet (I think it's OK to include options that only work in some or most browsers, but not options that don't work in any, or that only work in one).

**Comment by schalkneethling** [comment]
@wbamberg Same question here as in https://github.com/mdn/interactive-examples/pull/1145

**Comment by schalkneethling** [comment]
@estelle Because of the following security vulnerability https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream that was revealed yesterday, we are reaching out to everyone that currently has an open PR on interactive examples.

We ask that you please update your fork's master branch, and rebase your current feature branch against the new master. This will update the affected dependency to a version that is no longer affected, and remove the security concern.

We appreciate your assistance in this matter. Should you need any assistance, please feel free to reach out.

**Comment by schalkneethling** [comment]
I just tested and this works in Firefox, Safari, and Edge so I reckon is safe to merge now. @chrisdavidmills agree?

**Review by chrisdavidmills — APPROVED** [review]
Yup, let's get it done.

**Pull request merged**
