### PR TITLE
Implement vertical resize for JS code editor

### LINKED ISSUE #403: Idea: Make the interactive example code editor vertically resizable
To facilitate tinkering with examples in more and bigger and better ways, we should consider making the editor box for interactive examples resizable so the user can choose to have room for a larger number of lines of code than the initial sample code.

Just adding the ability to grab the bottom edge of the code box and drag it up and down to resize it would be a nice touch; have the rest of the interactive sample box and the surrounding page content move up and down as needed to make room.

### PR DESCRIPTION
**Pull request by kenrick95**
Fixes #403

([demo](https://giphy.com/gifs/xThtaw2UxnJBJUvMDC/fullscreen))

### CODE REVIEW

**Comment by schalkneethling** [comment]
This looks great @kenrick95 but, we have a bit of a problem. When this is embedded in a page on MDN, it lives inside an `iframe`. This means that the iframe needs to resize as the JS editor is resized. The problem is, the `iframe` is controlled by the MDN domain and not the interactive editor domain.

Currently we work around this using `pushMessage`, and we can surely do the same here to post height changes when the user stops resizing the editor. I wonder though, in its current iteration, if the amount fo code we are adding for this feature will provide a big enough payoff for end users to justify the performance impact. And then also the possible SEO impact of slower loading pages(although it might not be much, but Google seems to be cracking down ;)).

So I am on the fence about this one. @wbamberg your thoughts on this?

**Comment by wbamberg** [comment]
@kenrick95 , this is really cool work, but I'm sorry to say I agree with @schalkneethling. We should have commented to this effect in the bug before you put time into your solution, and I'm sorry we didn't.

I'm not as familiar as you with the likely impact of this on code complexity or performance, but my feeling is that we should not implement this bug now.

There are IMO more important issues we should look at. One I can think of would be https://github.com/mdn/interactive-examples/issues/534, about having more a robust and sophisticated way to deal with unsupported features. But I think there too we (where "we" is everybody :) need to discuss a bit further what we want to happen, before implementing a solution.

**Comment by kenrick95** [comment]
I see your points and I agree that it might not be wise to do this right now. Alright then, let's close this PR for now. Cheers.

**Comment by schalkneethling** [comment]
Thanks so much for understanding and your continued amazing work @kenrick95 We really appreciate it.

**Pull request closed without merging**
