### PR TITLE
Adds 7ayushgupta as a contributor

### PR DESCRIPTION
**Pull request by schalkneethling**

### CODE REVIEW

**Comment by schalkneethling** [comment]
@7ayushgupta thank you for your contributions o/\o

**Comment by 7ayushgupta** [comment]
Actually, this was one of my first contributions to a popular organization's repository.

**Comment by schalkneethling** [comment]
@7ayushgupta see https://github.com/mdn/interactive-examples#contributors

**Comment by 7ayushgupta** [comment]
Thanks, it made my day :smile: I'll try to solve more issues.

**Pull request merged**
