### PR TITLE
added path() value example, support in FF63 behind a flag.

### PR DESCRIPTION
**Pull request by estelle**
https://bugzilla.mozilla.org/show_bug.cgi?id=1246764

### CODE REVIEW

**Comment by schalkneethling** [comment]
@wbamberg Should we merge and revisit later when support is better or, would you rather close?

**Comment by wbamberg** [comment]
@schalkneethling is there a reason we can't leave this open? I appreciate that it would need rebasing after the big PR merge, but I don't think this one is ready to merge, but closing it seems a bit final.

**Comment by schalkneethling** [comment]
@estelle Because of the following security vulnerability https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream that was revealed yesterday, we are reaching out to everyone that currently has an open PR on interactive examples.

We ask that you please update your fork's master branch, and rebase your current feature branch against the new master. This will update the affected dependency to a version that is no longer affected, and remove the security concern.

We appreciate your assistance in this matter. Should you need any assistance, please feel free to reach out.

**Comment by schalkneethling** [comment]
Same here @chrisdavidmills, seems safe to merge now as it is supported in three browsers.

**Review by chrisdavidmills — APPROVED** [review]
Let's do it

**Pull request merged**
