### PR TITLE
Deploy interactive examples on merges to main

### PR DESCRIPTION
**Pull request by wbamberg**
This PR is intended to run the [`prod-deploy`](https://github.com/mdn/interactive-examples/actions/workflows/prod-deploy.yml) workflow when a push happens to the `main` branch, per:

- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs.
- https://github.com/orgs/community/discussions/26724#discussioncomment-3253093

@NiedziolkaMichal , @schalkneethling , does this look right? I'm not at all familiar with GH actions.

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
I think it looks ok. It should fix [#913](https://github.com/mdn/bob/issues/913).

@nschonni Could you please take a look? You seem to be acquainted with github workflow.

**Comment by nschonni** [comment]
LGTM, although maybe you want to keep the workflow_dispatch to allow manual triggering still

**Comment by wbamberg** [comment]
> LGTM, although maybe you want to keep the workflow_dispatch to allow manual triggering still

Good point @nschonni . Like this? https://github.com/mdn/interactive-examples/pull/2337/commits/625e6922a32cbf653571bf47cb3e631ebde0628b

**Comment by nschonni** [comment]
Yup, looks good

**Comment by NiedziolkaMichal** [comment]
Alright, on next merge we will find out if everything works fine

**Comment by wbamberg** [comment]
-> https://github.com/mdn/interactive-examples/pull/2328

**Comment by nschonni** [comment]
Looks like it's failing. Is the idea to keep publishing to an orphan branch with this job?

**Comment by NiedziolkaMichal** [comment]
I think only deployments triggered by [dependabot](https://github.com/apps/dependabot) fail, because [Array.of](https://github.com/mdn/interactive-examples/actions/runs/3500558961) worked out just fine. Pretty much all [publish-release workflows](https://github.com/mdn/interactive-examples/actions/workflows/publish-release.yml) of dependabot fail with reason `Input required and not supplied: token`

**Comment by nschonni** [comment]
Ah, the dependabot ones might fail because the automerge job. I think there are restrictions for bot things triggering other jobs

**Pull request merged**
