### PR TITLE
Adding at() examples

### PR DESCRIPTION
**Pull request by Rumyra**
Adding at() examples for array, string and typedarray

### CODE REVIEW

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
I've tested these, and they all work, nice one @Rumyra !

I think the string one is the best; I think you should update the array and typedarray ones so they follow suit — both should include a positive and a negative example, and a more descriptive console log, e.g. something like "The item at index number -2 is 40." (or whatever)

**Comment by chrisdavidmills** [comment]
Also, @schalkneethling , any thoughts on why the CI is failing for this? The added examples seem to run absolutely fine, so I'm not really sure why.

**Comment by schalkneethling** [comment]
@Rumyra @chrisdavidmills here is the failure reason:

```
/home/travis/build/mdn/interactive-examples/live-examples/js-examples/string/string-at.js
   5:79  error  Missing semicolon  semi
  10:79  error  Missing semicolon  semi
```

**Comment by chrisdavidmills** [comment]
> @Rumyra @chrisdavidmills here is the failure reason:
> 
> ```
> /home/travis/build/mdn/interactive-examples/live-examples/js-examples/string/string-at.js
>    5:79  error  Missing semicolon  semi
>   10:79  error  Missing semicolon  semi
> ```

Ah. How did you access that? I was looking everywhere for a list of error specifics

**Comment by Rumyra** [comment]
Thanks for the feedback @chrisdavidmills 👍 appreciated

I'll tidy up those failures while I'm at it 😬 thanks @schalkneethling

**Review by chrisdavidmills — APPROVED** [review]
Looking much better @Rumyra !

I have made a couple more small tweaks to the result string wording, and I think this is ready to merge now.

**Pull request merged**
