### PR TITLE
Example for async iterator on a Symbol

### PR DESCRIPTION
**Pull request by jpmedley**
This example is needed for a page that will be here: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator

### CODE REVIEW

**Comment by wbamberg** [comment]
If I'm not mistaken there's already a PR for this: https://github.com/mdn/interactive-examples/pull/1198 - @Elchi3 , can you pick one of these PRs to review and close the other one?

**Comment by jpmedley** [comment]
FWIW, I was originally going to submit something similar to #1198. Chrome Dev Rel's JS guy (Mathias Bynens) suggested this.

**Comment by jahzielv** [comment]
Hi @jpmedley and @wbamberg ! I'm working on an async iteration documentation effort with Daniel Ehrenburg and Willian Martins based on some notes created by @Elchi3 (we're tracking our work [over here](https://github.com/tc39/proposal-async-iteration/issues/132). Willian and I have been writing the https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator page the past couple of days, and I just wanted to check in and see what the status was on either this or #1198. The page is taking shape, and is ready for either interactive example when one is selected. Thanks for your help! :smile:

**Comment by Elchi3** [comment]
Sorry I have no bandwidth right now to review JS async docs. We'll need to see if we could add this as an item in the next team sprint and/or find someone to review it. @chrisdavidmills

**Comment by chrisdavidmills** [comment]
@Elchi3 you can always add this to the next sprint; you've only got a couple of 66-related DDN tasks to do for JS docs.

**Review by Elchi3 — CHANGES_REQUESTED** [review]
This needs an update to live-examples/js-examples/symbol/meta.json

See how this is done here: https://github.com/mdn/interactive-examples/pull/1198/files#diff-a153ba6c8a0c3bd224ce2443e9381877b488bbe487fc0a4c39a7988c3d93c7d6

**Comment by schalkneethling** [comment]
> This needs an update to live-examples/js-examples/symbol/meta.json
> 
> See how this is done here: [#1198 (files)](https://github.com/mdn/interactive-examples/pull/1198/files#diff-a153ba6c8a0c3bd224ce2443e9381877b488bbe487fc0a4c39a7988c3d93c7d6)

@jpmedley friendly ping 🐱

**Comment by Rumyra** [comment]
I'm going to close this due to inactivity - feel free to open again with meta.json edits

**Pull request closed without merging**
