### PR TITLE
updating section example

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Fixes https://github.com/mdn/content/issues/1370

### CODE REVIEW

**Comment by eeriksp** [comment]
Thank you! I this this is a nice improvement.

**Comment by chrisdavidmills** [comment]
@eeriksp cool, thanks. Let's get it merged!

**Comment by mattiapontonio** [comment]
https://en.m.wikipedia.org/wiki/Proper_and_common_nouns

**Comment by eeriksp** [comment]
@mattiapontonio are you referring to `apple` vs `Apple`?

**Comment by mattiapontonio** [comment]
@eeriksp yep... 👨‍🏫🤷🏻‍♂️

**Comment by eeriksp** [comment]
Yes, I agree. But this should be an easy thing to fix.

**Comment by mattiapontonio** [comment]
Yes It is
https://github.com/mdn/interactive-examples/edit/master/live-examples/html-examples/content-sectioning/section.html

**Pull request merged**
