### PR TITLE
Add JS Object.is()

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
Interactive example for [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is).

image

### CODE REVIEW

**Review by Josh-Cena — COMMENTED** [review]
LGTM, but maybe add two object examples?

```js
console.log(Object.is({}, {}));
const obj = {};
const obj2 = obj;
console.log(Object.is(obj, obj2));
```

**Comment by NiedziolkaMichal** [comment]
I am afraid it will cause the big version of JS example window to be displayed. Additionally, the output will not fit inside the console so scroll bar will appear:
image

**Comment by Josh-Cena** [comment]
Okay; maybe get rid of the last one and keep `Object.is({}, {})`? I mostly want to tell people that it's still "compare-by-reference".

**Comment by NiedziolkaMichal** [comment]
That's a good idea. I have changed the example a little bit, so it shows that:

- It doesn't do type coercion
- Treats NaN equal, unlike ===
- Treats -0 & 0 not equal, unlike ===
- Compares objects by reference, instead of shallow equal or sth else

Adding 1 more line would change the window height to tall.

image

**Review by Josh-Cena — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
