### PR TITLE
Adds sanity puppeteer test for CSS editor

### PR DESCRIPTION
**Pull request by schalkneethling**

### CODE REVIEW

**Comment by schalkneethling** [comment]
@wbamberg Are you still having trouble testing this one? I tested again locally and all tests are passing.

**Comment by schalkneethling** [comment]
@wbamberg Any opposition to merging this one? I tested locally and the tests all pass.

**Comment by wbamberg** [comment]
@schalkneethling , as I said, I get errors while running these. So I'm happy for you to merge if you would like - it's very probably some environment issue on my end - but I can't say it works for me.

**Comment by schalkneethling** [comment]
@wbamberg That is odd. It seems like the local server is not starting up for the tests. Wonder if you perhaps another instance running on the same port. Anyhow, seeing it passes for me locally and on Travis, I am going to go ahead and merge this, and the other PR.

I am also going to open a new PR to have the tests run on a different port than the dev server to avoid such collisions.

**Pull request merged**
