### PR TITLE
feat: showcase basic array functionality

### PR DESCRIPTION
**Pull request by hirehamir**
The goal of this is to add an interactive example to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array.

I did something similar for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map with #1855.

### CODE REVIEW

**Comment by hamirmahal** [comment]
## Demo after `yarn run build` and `yarn start`

https://user-images.githubusercontent.com/43425812/185542756-ca51552a-ff40-436b-becd-74d69657eb28.mp4

**Comment by hamirmahal** [comment]
I'm not sure how big of an issue it is, but the result of

```
git diff ca3a22dd3666e30454197f81eeaa61257a3c1bdb
```

includes this output.

```diff
     "pages": {
+        "array": {^M
+            "exampleCode": "./live-examples/js-examples/array/array.js",^M
+            "fileName": "array.html",^M
+            "title": "JavaScript Demo: Array",^M
+            "type": "js"^M
+        },^M
         "arrayAt": {
             "exampleCode": "./live-examples/js-examples/array/array-at.js",
             "fileName": "array-at.html",
```

I don't know how much of an issue the `^M`s will be.

**Comment by hamirmahal** [comment]
@Rumyra let me know if there is anything I can do to improve this pull request.

**Comment by NiedziolkaMichal** [comment]
Hey! What do you think about improving this example a little bit, so more features of an array are presented in a short example? I am thinking about following features, but you choose differently:
1. Arrays are zero-indexed and its values can be retrieved with []
2. Arrays can contain mix of different data types
3. It might also be good to show usage of length property, which is very common.

**Comment by Rumyra** [comment]
Sorry to take a while to get back - yes I love the idea of an example of the array page and agree with @NiedziolkaMichal here 

>Arrays are zero-indexed and its values can be retrieved with []
>Arrays can contain mix of different data types
>It might also be good to show usage of length property, which is very common.

How do you feel about that @hamirmahal ?

**Comment by hamirmahal** [comment]
@Rumyra that sounds excellent! I just implemented those changes.

**Comment by hamirmahal** [comment]
> Hey! What do you think about improving this example a little bit, so more features of an array are presented in a short example? I am thinking about following features, but you choose differently:
> 
> 1. Arrays are zero-indexed and its values can be retrieved with []
> 2. Arrays can contain mix of different data types
> 3. It might also be good to show usage of length property, which is very common.

Excellent suggestion! My recent changes should address this.

**Comment by hamirmahal** [comment]
> Hey! What do you think about improving this example a little bit, so more features of an array are presented in a short example? I am thinking about following features, but you choose differently:
> 
> 1. Arrays are zero-indexed and its values can be retrieved with []
> 2. Arrays can contain mix of different data types
> 3. It might also be good to show usage of length property, which is very common.

Excellent suggestions! My recent changes should address this.

**Comment by hamirmahal** [comment]
@Rumyra what changes would you like to see here before merging this pull request?

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
This seems overly loaded to me. IMO (but I'm not too keen with interactive examples anyway) the point of these examples are to give a "taste" of the feature, so the third example:

```js
const array2 = [123, 'abc', { objectWithAge: 67 }, null];
const nestedArrays = [
  array2,
  [],
  [
    [1, 2, 3],
    [4, 5, 6],
  ],
];
console.log(nestedArrays.length); // 3
```

Seems unnecessary. I think the first two are fine.

**Comment by hamirmahal** [comment]
That third example was to address previous comments saying to showcase arrays showing different types.

> Hey! What do you think about improving this example a little bit, so more features of an array are presented in a short example? I am thinking about following features, but you choose differently:
> 
> 1. Arrays are zero-indexed and its values can be retrieved with []
> 2. Arrays can contain mix of different data types
> 3. It might also be good to show usage of length property, which is very common.



> Sorry to take a while to get back - yes I love the idea of an example of the array page and agree with @NiedziolkaMichal here
> 
> > Arrays are zero-indexed and its values can be retrieved with []
> > Arrays can contain mix of different data types
> > It might also be good to show usage of length property, which is very common.
> 
> How do you feel about that @hamirmahal ?

**Comment by hamirmahal** [comment]
That third example was to address previous comments saying to showcase arrays having different types.

> Hey! What do you think about improving this example a little bit, so more features of an array are presented in a short example? I am thinking about following features, but you choose differently:
> 
> 2. Arrays can contain mix of different data types



> Sorry to take a while to get back - yes I love the idea of an example of the array page and agree with @NiedziolkaMichal here
> 
> > Arrays can contain mix of different data types
> 
> How do you feel about that @hamirmahal ?

**Comment by Josh-Cena** [comment]
To showcase "Arrays can contain mix of different data types", we can simply add a `names.push(null)` or something similar if you wish, but to me it's not highly necessary. WDYT?

**Comment by hamirmahal** [comment]
I think for now, we can leave this as is, but anyone who wants to make an
improvement to this in the future is welcome to do so.

**Review by Josh-Cena — APPROVED** [review]
Okay, let's do this. Thank you for sticking with us after so long!

**Comment by hamirmahal** [comment]
You’re welcome! I’m glad I could help.

**Pull request merged**
