### PR TITLE
add hyphenate-limit-chars example

### PR DESCRIPTION
**Pull request by chrisdavidmills**
As part of my work on the [CSS `hyphenate-limit-chars` property](https://docs.google.com/document/d/1aLdSuLdZEMjdnMpeyBRdwwZyLr1JMbQ39Nk0ZWumLBU/edit#) (added to Chrome in version 109), I have added an interactive example for it.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi there @NiedziolkaMichal ! Are you able to review this PR this week? If not, no problem. Let me know and I can try to find someone else.

**Comment by NiedziolkaMichal** [comment]
Hey! Unfortunately, it's not supported on Chrome and Firefox yet, so it cannot be published. There is a new version of BOB(component showing the examples) that provides an informative fallback when an example is not supported on user's browser. When it gets into production and a stable version of Chrome will support this feature, I will be very happy to review and merge `hyphenate-limit-chars`.

**Comment by chrisdavidmills** [comment]
@NiedziolkaMichal It does work in Chrome Canary, but not Chrome Stable as yet. Is the policy to not publish examples until they work in a stable browser version? If so, that sounds reasonable to me.

**Comment by NiedziolkaMichal** [comment]
Yeah, for a while now we try to publish only those examples which work well on firefox and chrome. Currently, when feature is not supported by the users browser, he sees something like that:
image

The newer version is more informative, so I think it will be ok to publish also those examples, which are supported only by a single browser:
image

**Comment by chrisdavidmills** [comment]
Yup, that definitely looks better.

**Comment by NiedziolkaMichal** [comment]
I will ping you when the new BOB gets deployed, so we can merge this example.

**Review by queengooborg — APPROVED** [review]
It looks like this is only blocked on a new BoB release -- of which has landed since the last comment.  As such, I'm approving and merging this!

**Pull request merged**
