### PR TITLE
Normalize JS comments

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
This PR fixes plenty of minor issues in JS comments:
- There is now always an empty space immediately after `//`
- String output is now always wrapped into quotes
- Array output now always starts with the word `Array`
- Comment message starts with a lowercase
- Fixed a few instances of `expected output:` text missing or malformed
- Removed comments about bigint not being supported by all browsers

### CODE REVIEW

**Comment by Josh-Cena** [comment]
> Comment message starts with a lowercase

That's unfortunately against the code example guideline. I don't know what the convention here is but just want to point that out.

Also it's unfortunate that we add the `Array`/`Object` prefix to every console output—that's a lot of noise, especially for nested arrays.

**Comment by NiedziolkaMichal** [comment]
In such case, I think it might be better to alter comments so they start with an upper case letter. There are about 160 ordinary comments and 1147 `expected output` comments.
@wbamberg @bsmth do you think all of those comments should be changed so they fit the guidelines of examples in the content repository?

It's important to put `Array` and `Object` keywords, so they fit exactly with the output. For `Array.flat` it shows:
image

**Comment by Josh-Cena** [comment]
Yeah, for `Array`/`Object` I mean that the runner's console output includes the keywords.

**Comment by wbamberg** [comment]
> In such case, I think it might be better to alter comments so they start with an upper case letter. There are about 160 ordinary comments and 1147 `expected output` comments. @wbamberg @bsmth do you think all of those comments should be changed so they fit the guidelines of examples in the content repository?

I think that would be a good idea.

> It's important to put `Array` and `Object` keywords, so they fit exactly with the output. For `Array.flat` it shows: image

+1

This is a nice update, @NiedziolkaMichal ! Do you want to merge this and then fix initial letters in a follow-up?

**Comment by wbamberg** [comment]
> Yeah, for `Array`/`Object` I mean that the runner's console output includes the keywords.

I guess it was written to align with the Firefox console, but the Chrome console omits them. I like them FWIW but 
I would be OK to remove them if people feel strongly about it.

**Comment by Josh-Cena** [comment]
Yeah, but Firefox omits the keyword for nested arrays, making the `flat` example's output look less cluttered.

**Comment by NiedziolkaMichal** [comment]
I reverted the change of letter case from this PR. Later I will make the next one, changing the first letters of most of the comments to upper case.

**Review by Josh-Cena — APPROVED** [review]

**Pull request merged**
