### PR TITLE
Add <cite> example

### LINKED ISSUE #768: [HTML Examples] Inline text semantics ~ cite
Need an HTML example for the `cite` element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite

## Contributing

https://github.com/mdn/interactive-examples/blob/master/CONTRIBUTING-HTML.md

### PR DESCRIPTION
**Pull request by Elchi3**
Example for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite

Nothing really fancy. Let me know if you have other ideas.

Fixes #768

### CODE REVIEW

**Comment by wbamberg** [comment]
I think it's fine for an example to be simple, but I'm not sure this is a good example of a citation. I think of a citation as a reference: that is, a link *from* some content that draws on a work (or even a quote from a work) *to* the work itself: so that, for example, someone interested in checking the sources can go and find them. For example, the "Notes" in a Wikipedia article use `<cite>`: https://en.wikipedia.org/wiki/Pythagorean_theorem#cite_note-Sally0-1.

There are also some nice examples of what I mean here:  http://html5doctor.com/cite-and-blockquote-reloaded/

Would it be possible to cook up some example like this? Does that make sense?

**Comment by Elchi3** [comment]
Thanks Will. I think the WHATWG and W3C specs disagree here. I was reading the WHATWG definition and it says "The cite element represents the title of a work" whereas the W3C says "The cite element represents a reference to a creative work."

**Comment by Elchi3** [comment]
I've used this in combination with a `<blockquote>` element now and made `<cite>` a full reference to a work instead of just a title of a work.

**Comment by Elchi3** [comment]
Rebased again

**Comment by wbamberg** [comment]
>  I think the WHATWG and W3C specs disagree here. I was reading the WHATWG definition and it says "The cite element represents the title of a work" whereas the W3C says "The cite element represents a reference to a creative work."

Interesting. It seems like our docs could be better here. I was more going be the generally accepted meaning of "citation", and the way it seemed to be used. Anyway, I like this example better, so thanks for making the changes.

**Pull request merged**
