### PR TITLE
feat: add JavaScript to code snippet

### LINKED ISSUE #2535: Demo for <input type=url> does not demonstrate validation
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

### What specific section or headline is this issue about?

Try it (HTML demo)

### What information was incorrect, unhelpful, or incomplete?

The demo doesn't demonstrate the browser validation for `required` or `pattern`, because it is not inside a `<form>` (at least, not in my Chrome).
I suggest it is wrapped in a simple `<form>` element, see below.

### What did you expect to see?

```
<form>
  <label for="url">Enter an https:// URL:</label>

  <input type="url" name="url" id="url"
       placeholder="https://example.com"
       pattern="https://.*" size="30"
       required>
</form>
```

Screen Shot 2023-06-02 at 9 58 19 am
Screen Shot 2023-06-02 at 9 58 23 am

Note that this doesn't provide any feedback when the submit is successful, it simply clears the form. Perhaps we could add a little javascript to catch the submit and provide a success message instead.

### Do you have any supporting links, references, or citations?

As on the same page (emphasis added)  😉 

> The input value is automatically validated to ensure that it's either empty or a properly-formatted URL before the **form** can be submitted. 

### Do you have anything more you want to share?

I was unable to find a way to submit a PR for this, because these examples don't appear to be in the repository. I searched for the below path with GitHub's "Go to file" tool, but had no luck.

```
{{EmbedInteractiveExample("pages/tabbed/input-url.html", "tabbed-shorter")}}
```

There's nothing mentioned in the readme or contributing.md files, can details be added about this?

### PR DESCRIPTION
**Pull request by CBID2**
### Description
This PR adds JavaScript to the code snippet in the HTML input example.

### Motivation
[David Cook](https://github.com/mdn/interactive-examples/issues/2535) mentioned that the demo doesn't demonstrate the browser validation for required or pattern, because it is not inside a `<form>`. By adding JavaScript to it, the example will work.

### Additional details

[Example where the issue takes place ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url)

### Related issues and pull requests

Fixes #2535

### CODE REVIEW

**Review by estelle — COMMENTED** [review]
The `EmbedInteractiveExample` macro works in the /mdn/content/ directory. 
This directory contains the examples that are embedded using the `EmbedInteractiveExample` within MDN. In other words, this repo contains HTML, CSS, and JS, which is can then be pulled into MDN pages using the macro.

To solve the issue raised, you would want to update the code to include a `<form>`. The form with no `action` will submit to itself, reloading the example in place.

**Comment by CBID2** [comment]
> The `EmbedInteractiveExample` macro works in the /mdn/content/ directory. This directory contains the examples that are embedded using the `EmbedInteractiveExample` within MDN. In other words, this repo contains HTML, CSS, and JS, which is can then be pulled into MDN pages using the macro.
> 
> To solve the issue raised, you would want to update the code to include a `<form>`. The form with no `action` will submit to itself, reloading the example in place.

Ok @estelle, I added the form element.

**Comment by estelle** [comment]
> > The `EmbedInteractiveExample` macro works in the /mdn/content/ directory. This directory contains the examples that are embedded using the `EmbedInteractiveExample` within MDN. In other words, this repo contains HTML, CSS, and JS, which is can then be pulled into MDN pages using the macro.

This part needs to be addressed.

> > To solve the issue raised, you would want to update the code to include a `<form>`. The form with no `action` will submit to itself, reloading the example in place.
> 
> Ok @estelle, I added the form element.

while a label works anywhere in the page, visually the label with the form control it's labelling is vital. Best practices is to put the label next to the input, before the input in most cases, but after a checkbox or radio button. In other words, the label should be in the form. 

so, the EmbedInteractiveExample needs to be removed, the label needs to be moved to be in the form, and no js was added, but not sure if it needs any

**Comment by CBID2** [comment]
> > > The `EmbedInteractiveExample` macro works in the /mdn/content/ directory. This directory contains the examples that are embedded using the `EmbedInteractiveExample` within MDN. In other words, this repo contains HTML, CSS, and JS, which is can then be pulled into MDN pages using the macro.
> 
> This part needs to be addressed.
> 
> > > To solve the issue raised, you would want to update the code to include a `<form>`. The form with no `action` will submit to itself, reloading the example in place.
> > 
> > 
> > Ok @estelle, I added the form element.
> 
> while a label works anywhere in the page, visually the label with the form control it's labelling is vital. Best practices is to put the label next to the input, before the input in most cases, but after a checkbox or radio button. In other words, the label should be in the form.
> 
> so, the EmbedInteractiveExample needs to be removed, the label needs to be moved to be in the form, and no js was added, but not sure if it needs any

Hi @estelle! :) I made the changes.

**Review by estelle — APPROVED** [review]
Thanks! 🎉

**Comment by dacook** [comment]
Thanks @CBID2 and @estelle for working through this one, it works perfectly now!

Sorry for causing confusion with the mention of the input-url.html file; it was all I could figure out at the time.

**Comment by CBID2** [comment]
> Thanks @CBID2 and @estelle for working through this one, it works perfectly now!
> 
> Sorry for causing confusion with the mention of the input-url.html file; it was all I could figure out at the time.

No problem @dacook! :) We're glad that this makes the documentation clearer now! :)

**Pull request merged**
