### PR TITLE
Functions circle, ellipse, inset, polygon, path

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
Interactive examples for basic-shape functions: [circle](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/circle), [ellipse](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/ellipse), [inset](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/inset) and [polygon](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/polygon). Theme is the same as in [basic-shape](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape).

image
image
image
image

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
I have also added [path](https://developer.mozilla.org/en-US/docs/Web/CSS/path)
image

**Review by wbamberg — COMMENTED** [review]
Thanks @NiedziolkaMichal !

I think `circle()`, `ellipse()`, and `inset()` are fine (although some of them overflow a bit) but as with `repeating-conic-gradient`, for especially `path()` and `polygon`, I worry that the syntax is not very visible or comprehensible. Maybe again it's worth having fewer simpler examples and using multiple lines to keep it readable, like

```
clip-path: path(
 'M  20 240  L  20  80
  L 160  80  L 160  20
  L 280 100  L 160 180
  L 160 120  L  60 120
  L  60 240 Z');

clip-path: path(
 'M 20 240
  C 20 0 300 0 300 240 Z');
```

?

**Comment by NiedziolkaMichal** [comment]
@wbamberg Unfortunately I don't think it can be done so easily. Line break is incorrectly interpretted in middle of a string and the whole example is not applied:
image

It would require placing `\` before every line ending, just like that:
image

What do you think?

**Comment by wbamberg** [comment]
Hm, nasty. Personally I think the version with the `\` line breaks is still better than the version on one line. I mean, the one-line version is really unusable, and at least like that we can see all the syntax.

**Comment by wbamberg** [comment]
Thank you for the update @NiedziolkaMichal !

What do you think about doing this for `polygon()`:

```css
clip-path: polygon(10px 10px,
                  110px 10px,
                   60px 60px);

clip-path: polygon(50% 0%,
                  100% 50%,
                   50% 100%, 
                    0% 50%);
```

...I think this helps to show the syntax of `polygon()`, as a series of coordinates.

**Comment by NiedziolkaMichal** [comment]
Sure. I have updated example and now it looks like this:
image

**Review by wbamberg — APPROVED** [review]
👍 I like the arrow version, much more interesting than mine. These are great @NiedziolkaMichal .

**Pull request merged**
