### PR TITLE
Adds interactive example for `overscroll-behavior`

### LINKED ISSUE #1639: CSS examples: need examples for overscroll-behavior and its related properties
See https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior - this property controls aspects of the browser's behavior when the user reaches the end of a scrolling box.

For example, when a scrolling box is placed inside another scrolling box, then by default, when the user reaches the end of the inner box, the outer box will start to scroll. The `overscroll-behavior` property can be used to prevent this behavior.

There are I think 5 properties that need interactive examples in total:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-x
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-block
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-inline

It would be fine for all 5 examples to be variations on a single pattern.

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-block#Examples has a live sample that could give some pointers to how to implement an interactive example.

### PR DESCRIPTION
**Pull request by anirudh-modi**
Partially fixes #1639 

While, the original issue asked for demo example for `overscroll-behavior`. I am intending to fix them incrementally for each property individually.

### CODE REVIEW

**Comment by anirudh-modi** [comment]
Hi @wbamberg This is a fix for the issue #1639 , while I am aware, that the description of the issue asked for other properties as well, I was hoping to start with `overscroll-behavior` and then incrementally add them in subsequent PRs..

Any feedback is welcome.

**Review by wbamberg — APPROVED** [review]
Thanks @anirudh-modi , I think this looks great!

**Comment by wbamberg** [comment]
@anirudh-modi , thanks for this contribution! If we want to see the changes on MDN, we need to tell the [`overscroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) page on MDN about this example, by adding something like this:

```
{{EmbedInteractiveExample("pages/css/overscroll-behavior.html")}}

## Syntax
```

...to the page at https://github.com/mdn/content/blob/main/files/en-us/web/css/overscroll-behavior/index.md, immediately after the intro paragraph:

```
The **`overscroll-behavior`** CSS property sets what a browser does when reaching the boundary of a scrolling area. It's a shorthand for {{cssxref("overscroll-behavior-x")}} and {{cssxref("overscroll-behavior-y")}}.
```

(See for example https://developer.mozilla.org/en-US/docs/Web/css/border-left-width )

Please let me know whether you want to do this or not, otherwise I will :).

**Comment by anirudh-modi** [comment]
Hi @wbamberg Let me those changes, I had earlier looked into the change I need to do for the same.. I will raise a PR in the other repo by EOD..

**Comment by anirudh-modi** [comment]
Hi @wbamberg I seem to be getting an like this... should this be happening?

Screenshot 2021-08-31 at 9 49 26 AM

**Comment by wbamberg** [comment]
@schalkneethling , I'm not seeing this page deployed to https://interactive-examples.mdn.mozilla.net/pages/css/overscroll-behavior.html, although it seems to be in the right place and I can see it running interactive examples locally at http://127.0.0.1:9090/pages/css/overscroll-behavior.html . Do you have any idea what might be going on here?

**Comment by schalkneethling** [comment]
> @schalkneethling , I'm not seeing this page deployed to https://interactive-examples.mdn.mozilla.net/pages/css/overscroll-behavior.html, although it seems to be in the right place and I can see it running interactive examples locally at http://127.0.0.1:9090/pages/css/overscroll-behavior.html . Do you have any idea what might be going on here?

I know we had an issue with Travis where we ran out of credits or something such. Will have to have a look. Will ask the folks in Infra

**Comment by wbamberg** [comment]
This is working now! Thanks @escattone for sorting it out 👍 https://github.com/mdn/content/issues/2372#issuecomment-915376364 .

**Comment by anirudh-modi** [comment]
Awesome...


@wbamberg I have already created a Pr in content..

https://github.com/mdn/content/pull/8482

**Comment by schalkneethling** [comment]
> This is working now! Thanks @escattone for sorting it out 👍 [mdn/content#2372 (comment)](https://github.com/mdn/content/issues/2372#issuecomment-915376364) .

Also, interactive examples switched to GitHub Actions so, we should start seeing regular releases again!

**Pull request merged**
