### PR TITLE
Add idle workflow

### PR DESCRIPTION
**Pull request by MrBrain295**

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
Honestly, I don't see any value in adding `idle` tag to all of those old PRs, that are awaiting BOB update or better browser support.

**Comment by MrBrain295** [comment]
See: https://github.com/mdn/mdn/issues/300

**Comment by NiedziolkaMichal** [comment]
@MrBrain295 Alright, I wasn't aware.

**Comment by bsmth** [comment]
Thanks both, it looks like this has already landed. These are being added across all MDN repos for consistency. Let us know your thoughts on the interval used to determine `idle` etc.

Going to close now 👍🏻

**Comment by bsmth** [comment]
BTW, the defaults for the workflow are here: https://github.com/mdn/workflows/blob/main/.github/workflows/idle.yml

There's probably a way to override the inputs for "number days stale" per repo to adjust to how we want it here.

https://github.com/mdn/workflows/blob/main/.github/workflows/idle.yml#L20-L24

**Pull request closed without merging**
