### PR TITLE
updates hgroup example

### PR DESCRIPTION
**Pull request by scottaohara**
per recent changes to `hgroup` element, reflected in the updated content of the [`hgroup`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup) MDN doc, the try it example needed to be updated as well.

replaced `h2` element with `p` element

### CODE REVIEW

**Comment by jasikpark** [comment]
++ for this change, the description below the example describes that a single heading element is permitted, while the current example has two.

image
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup#try_it

**Comment by jasikpark** [comment]
same info here: https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model

**Comment by scottaohara** [comment]
@estelle per the updates i made to the `hgroup` article the other day, this example needed to be updated as well.  Is there a separate team that reviews changes to this repo?

**Comment by estelle** [comment]
@scottaohara The interactive examples are in a separate repo: https://github.com/mdn/interactive-examples. 

I am not sure who generally reviewed these. I was added to that repo last week, so have been reviewing a backlog. if you mention me with @estelle, I will see it in my notifications, which I tend to check at least every other day.

**Review by estelle — APPROVED** [review]
thank you

**Comment by estelle** [comment]
i happen to be in there right now, so I'll make the edit.

**Comment by jasikpark** [comment]
woot 🥳

**Pull request merged**
