### PR TITLE
Add example for JavaScript 'super' keyword

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
Interactive example for keyword [super](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super). It shows how super can be used in constructor and also to access methods from superclass. I hope it's not too complex.

image

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @NiedziolkaMichal thanks a lot! 🙌🏻  Side note: the title is really useful to get an idea of the PR contents. I've updated this one so the reviewer can see from the open PRs what the contents are from a format like this:

```
[Added/Edited/Removed] the [technology type] [specific property]
```

**Comment by NiedziolkaMichal** [comment]
@bsmth Thank you

**Review by bsmth — APPROVED** [review]
LGTM 👍🏻

**Comment by NiedziolkaMichal** [comment]
Thanks for review

**Pull request merged**
