### PR TITLE
Add html input range

### PR DESCRIPTION
**Pull request by wbamberg**
I didn't show ticks, due to dodgy browser support. But let me know if you'd like it.

### CODE REVIEW

**Comment by wbamberg** [comment]
> Can we please have the volume control going from 0 to 11? not joking ;-)

I was totally going to do this! Then I forgot :).

**Comment by wbamberg** [comment]
I also wanted to have labels for the cowbell like "more" and "even more". Gutted that this is not supported by browsers yet.

**Comment by wbamberg** [comment]
Updated! Please take another look.

**Comment by chrisdavidmills** [comment]
perfect! r+

**Pull request merged**
