### PR TITLE
Add `list-style-position` css example

### PR DESCRIPTION
**Pull request by d7ark**
Hello. My very first pull request for mdn. I hope everything is alright. Pull's related to #481 
I've made two lists ul and ol to highlight that list-style-position works for both.

Looking forward to the feedback (especially on how to make it prettier).

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for contributing!

I think this is generally very good: however, @helmutgranda just landed an example for the shorthand of this property, `list-style`:
https://developer.mozilla.org/en-US/docs/Web/CSS/list-style
https://interactive-examples.mdn.mozilla.net/pages/css/list-style.html

For consistency, I think it would be great if the `list-style-position` example used the same basic example as the `list-style` example: this means the same CSS file, unless that's not possible, and the same HTML contents, unless that's not possible.

@d7ark, what do you think? I'm sorry not to have made this clear in the bug.

**Comment by d7ark** [comment]
It's fine. No problem. It's definitely doable.

I've even seen those changes as pull request. Should've thought of making mine similar. Ill change it and post new version.

Thanks.

**Comment by schalkneethling** [comment]
> So I'm going to merge this and fix it up later, probably by moving list-style into "lists". But I'd also welcome @schalkneethling 's input :)

I agree @wbamberg

**Comment by wbamberg** [comment]
I just updated the MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position :)

**Pull request merged**
