### PR TITLE
line-break

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
Interactive Example for [line-break](https://developer.mozilla.org/en-US/docs/Web/CSS/line-break), suggested in issue [#1642](https://github.com/mdn/interactive-examples/issues/1642).

image

### CODE REVIEW

**Review by mfuji09 — CHANGES_REQUESTED** [review]
This text isn't understandable.
Here's an example I have made for this property.
(It should be displayed in `width: 14em;`)

この喫茶店は、いつでもコーヒーの香りを漂わせています。\<br>彼女はこの喫茶店で働いて、着々と実力をつけていきました。\<br>今では知る人ぞ知る、名人です。

**Comment by mfuji09** [comment]
My browser (Firefox) produces different result between "normal" and "loose". "loose" splits the word "着々" into two lines.
Screen Shot 2022-05-18 at 00 07 37

**Comment by NiedziolkaMichal** [comment]
I also tested it on firefox, but after seeing the pictures, I noticed that you are using different font. Could you please tell me which font is used by your browser, so I can attach it to the example?

**Comment by mfuji09** [comment]
Can you test it with this CSS?
#example-element {
	font-family: "Yu Gothic", "YuGothic", "Meiryo", "ＭＳ ゴシック", sans-serif;
	border: 2px dashed #999;
	text-align: left;
	width: 14em;
}

**Review by mfuji09 — APPROVED** [review]
Thank you!

**Review by wbamberg — APPROVED** [review]
👍 thank you @NiedziolkaMichal , and for your help too @mfuji09 , much appreciated!

**Pull request merged**
