### PR TITLE
Fix nesting depth in Array.prototype.flat example

### PR DESCRIPTION
**Pull request by bodograumann**
Nesting is reduced one level by array.flat. I have removed one level of nesting from the input to fix the semantics and at the same time make it more readable, while still illustrating the point.

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for the PR, @bodograumann , and I'm sorry to take so long to review this PR.

I'm not sure what "fix the semantics" means in this case, but I do think the current example is showing something that this version is not: namely that the argument is flattening to exactly the level given and not any further, so the array is not fully flattened. This seems like a useful thing to show in the example.

**Comment by bodograumann** [comment]
After another look, it seems I overlooked the `depth` parameter.
I’ll need to think about this some more.

**Comment by bodograumann** [comment]
What do you think about this approach, @wbamberg ?

**Comment by wbamberg** [comment]
This misses the case where the argument is > the nesting level, but I don't think that is so important to show, and I don't want this demo to be longer.

**Comment by bodograumann** [comment]
I like the idea a lot. Is the output represenation usual for MDN examples? In the firefox console I see:
Screenshot_20220610-161850

**Comment by wbamberg** [comment]
> I like the idea a lot. Is the output represenation usual for MDN examples? In the firefox console I see: Screenshot_20220610-161850

For the interactive examples we override the Firefox console implementation so as to log results into the example output pane instead of the own console. The output isn't always formatted in the same way - there's no particular good reason for this, but the form we give in `//expected output` should match the form people see when they click the "Run" button.

(you'll also note differences between the Firefox console and the Chrome console - the way consoles format output is not standardised).

**Comment by bodograumann** [comment]
How about using `Infinity` instead of `3` for the last variant?

**Comment by bodograumann** [comment]
I’ve commited your proposal modulo the `Infinity` example, which I think is the second most-common use-case after not using any `depth` parameter.

**Comment by bodograumann** [comment]
I have rebased on main.

**Review by bsmth — APPROVED** [review]
Looks good to me, leaving a +1

Any objections @wbamberg?

**Review by wbamberg — APPROVED** [review]

**Pull request merged**
