### PR TITLE
Issue 1138: embedded content

### PR DESCRIPTION
**Pull request by wbamberg**
Part of #1138: this part addressed the examples in the "embedded content" category, following the notes in column C of https://docs.google.com/spreadsheets/d/1EC23mRNF7i-Bd29A4wEcFV_iiThL1P-NBtH4lzme8eM/edit#gid=0. Generally minor updates to make the examples a bit simpler and more compact.

Most notably this replaces the video with a CC0 licensed one (https://pixabay.com/en/videos/red-flower-summer-color-colorful-14840/). I haven't yet removed the old video because it's still used in some other examples (e.g. [video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)).

I didn't shorten the name of the image file for the [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) example (as the notes in the spreadsheet ask) because that was done already, in https://github.com/mdn/interactive-examples/pull/1191. For some reason that's not showing up in the pages yet. Maybe it's being cached or maybe there's a problem there, I'll keep an eye on it :).

I haven't changed indentation to 2 spaces as per the new style guidelines. I'd rather address this (and any other changes from that) separately.

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks, good catch with the widths.

**Comment by wbamberg** [comment]
@schalkneethling , do you understand what this Travis error is and how I can fix it?

**Comment by schalkneethling** [comment]
@wbamberg It seems there is a weirdness between package-lock and package.json that is making npm i sad. I am going to ensure these are in sync, open a PR and merge it to master.

Should both the PR and merge commit pass Travis, I reckon you can rebase against master and all should be well. Will drop a note in here once the above is done.

**Comment by wbamberg** [comment]
Thank you @schalkneethling ! This seems like it might be connected to the weirdness around the file-renaming PR too (https://github.com/mdn/interactive-examples/pull/1191#issuecomment-433168477). I should try to learn this stuff...

**Comment by schalkneethling** [comment]
@wbamberg Ok, the pull request and merge commit both passed. Rebase against master and push, and let's see if it makes Travis happy ;)

**Comment by wbamberg** [comment]
\o/

**Pull request merged**
