### PR TITLE
ci(prod-deploy): use aws-cli, remove jenkins

### PR DESCRIPTION
**Pull request by caugner**
### Description

Migrates the prod-deploy workflow by replicating the stage-deploy, which uses aws-cli instead of Jenkins.

### Motivation

Simplifies the deployment and removes the dependency on Jenkins.

### Additional details

**Note**: Afterwards we can remove the `prod` branch.

### CODE REVIEW

**Comment by caugner** [comment]
The Prod Deployment on this branch [succeeded](https://github.com/mdn/interactive-examples/actions/runs/4294961771/jobs/7484716707), and after invalidating the CloudFront distribution, the interactive examples still work as expected.

**Comment by NiedziolkaMichal** [comment]
Isn't it better to keep `paths` condition? So PRs like #2461 or #2462 won't trigger automatic deployment.

**Comment by caugner** [comment]
> Isn't it better to keep `paths` condition?

That makes sense, but maybe we can do that in a separate PR, and apply the same paht filters to `stage-deploy`?

**Comment by NiedziolkaMichal** [comment]
@caugner Sure

**Review by NiedziolkaMichal — APPROVED** [review]

**Comment by NiedziolkaMichal** [comment]
@caugner Secrets `PROD_AWS_ACCESS_KEY_ID` and `PROD_AWS_ACCESS_KEY_SECRET` have been correctly set up, so we can merge this?

**Comment by caugner** [comment]
> Secrets `PROD_AWS_ACCESS_KEY_ID` and `PROD_AWS_ACCESS_KEY_SECRET` have been correctly set up, so we can merge this?

Yes, I've made a test run here: https://github.com/mdn/interactive-examples/actions/runs/4294961771

**Comment by NiedziolkaMichal** [comment]
Ok, I will merge #2469 and we will see if everything works ok.

**Comment by NiedziolkaMichal** [comment]
It works well. Thank you @caugner

**Pull request merged**
