### PR TITLE
no need constructor at all

### PR DESCRIPTION
**Pull request by totalamd**

### CODE REVIEW

**Comment by wbamberg** [comment]
I don't know this very well, but my understanding is:

******
Providing your own constructor using `constructor` is optional.

If you don't provide your own constructor, you will get a default constructor whose behavior is as described here: [Default constructors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor#Default_constructors). Note that for derived classes, the default constructor calls the parent class constructor.

If you need to do any other custom initialization, you need to provide your own constructor, using the `constructor` method. If you provide your own constructor in a derived class, then you should explicitly call the parent class constructor using `super`.
******

@Elchi3 , can you confirm that this is correct? I wonder if we should add this somewhere in the docs, with a helpful example. I couldn't see it spelled out like this anywhere.

**Comment by Elchi3** [comment]
Yes, I think you're right @wbamberg! Maybe we should expand the section on the constructor page to say this a bit better? This example is shown on the [extends](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/extends) page, though, and I see the same code used in the examples section on that page. It claims to be from https://googlechrome.github.io/samples/classes-es6/ but in all these contexts, it seems to me, the constructor could indeed be omitted. So, probably we should at least also fix our inline sample code that someone got in there from the google code page and that then it made its way into the interactive example :-)

The section "Derived Class Constructors" in https://hacks.mozilla.org/2015/08/es6-in-depth-subclassing/ also describes what's going on a bit more.

**Comment by wbamberg** [comment]
@Elchi3 since we can't properly review Wiki edits I'd like to put here what I was thinking of adding into the **Description** section of https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor . I would also remove the [Default constructors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor#Default_constructors) section as I would cover the same ground in **Description**. The examples are a bit silly, so any improvements would be welcome, but I do think they ought to be kept short.

******

## Description

There can be only one special method with the name "constructor" in a class. Having more than one occurrence of a constructor method in a class will throw a {{jsxref("SyntaxError")}} error.

A constructor enables you to provide any custom initialization that must be done before any other methods can be called on an instantiated object.

```js
class Person {

  constructor(name) {
    this.name = name;
  }

  introduce() {
    console.log(`Hello, my name is ${this.name}`);
  }

}

const otto = new Person('Otto');

otto.introduce();
```

If you don't provide your own constructor, then a default constructor will be supplied for you. If your class is a base class, the default constructor is empty:

```js
constructor() {}
```

If your class is a derived class, the default constructor calls the parent constructor, passing along any arguments that were provided:

```js
constructor(...args) {
  super(...args);
}
```


That enables code like this to work:

```js
class MyHardcodedBirthdayTester extends Date {

  isItMyBirthday() {
    const myMonth = 3;
    const myDate = 21;

    return (this.getMonth() === myMonth) && (this.getDate() === myDate);
  }

}

const tester1 = new MyHardcodedBirthdayTester('April 21, 2020');
console.log(tester1.isItMyBirthday());                     // true

const tester2 = new MyHardcodedBirthdayTester('March 19, 2020');
console.log(tester2.isItMyBirthday());                    // false
```

The MyHardcodedBirthdayTester class doesn't need an explicit constructor, because it doesn't need to do any custom initialization. The default constructor then takes care of initializing the parent Date from the argument it is given.

However, if you provide your own constructor, and your class derives from some parent class, then you must explicitly call the parent class constructor using `super`. For example:

```js
class MyBirthdayTester extends Date {

  constructor(dateStr, birthdayMonth, birthdayDate) {
    super(dateStr);                                      // call parent class constructor
    this.birthdayMonth = birthdayMonth;
    this.birthdayDate = birthdayDate;
  }

  isItMyBirthday() {
    return (this.getMonth() === this.birthdayMonth) && (this.getDate() === this.birthdayDate);
  }

}

const tester1 = new MyBirthdayTester('April 21, 2020', 3, 21);
console.log(tester1.isItMyBirthday());                     // true

const tester2 = new MyBirthdayTester('March 19, 2020', 3, 21);
console.log(tester2.isItMyBirthday());                    // false
```
*****

...or maybe this is too much, and it would be OK without the examples.

**Comment by Elchi3** [comment]
Thank you @wbamberg! I think what you propose is very useful. The birthday example is very made up and I think a real example would be good to see this stuff in action. I think a somewhat more realistic and common example would be to subclass `Error`. Maybe something like this? (please feel free to improve it further).

*****

That enables code like this to work:

```js
class ValidationError extends Error {

  printCustomerMessage() {
    return `Validation failed :-( (details: ${this.message})`;
  }

}

try {
  throw new ValidationError("Not a valid phone number");
} catch (error) {
   if (error instanceof ValidationError) {
    console.log(error.name); // This is Error instead of ValidationError!
    console.log(error.printCustomerMessage());
  } else {
    console.log('Unknown error', error);
    throw error;
  }
}

```

The `ValidationError` class doesn't need an explicit constructor, because it doesn't need to do any custom initialization. The default constructor then takes care of initializing the parent `Error` from the argument it is given.

However, if you provide your own constructor, and your class derives from some parent class, then you must explicitly call the parent class constructor using `super`. For example:

```js
class ValidationError extends Error {

  constructor(message) {
    super(message);  // call parent class constructor
    this.name = 'ValidationError';
    this.code = '42';
  }

  printCustomerMessage() {
     return `Validation failed :-( (details: ${this.message}, code: ${this.code})`;
  }

}

try {
  throw new ValidationError("Not a valid phone number");
} catch (error) {
   if (error instanceof ValidationError) {
    console.log(error.name); // Now this is ValidationError!
    console.log(error.printCustomerMessage());
  } else {
    console.log('Unknown error', error);
    throw error;
  }
}

```
*****

**Comment by wbamberg** [comment]
> Maybe something like this?

This is much better! I've updated the page: https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor#Description. I think it's helpful to have this extra detail.

I still need to fix the merge conflicts and merge the original PR :).

**Comment by Elchi3** [comment]
Very nice work, Will!

**Pull request merged**
