### PR TITLE
Change `expected output` to `Expected output`

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
This PR changes all `// expected output` to `// Expected output`, so comments follow the guidelines of examples from the content repository. I have decided to split this change into 2 separate PRs, making them easier to review.

### CODE REVIEW

**Comment by bsmth** [comment]
Hey @NiedziolkaMichal some conflicts here, unfortunately 😢

Do you want to take a look?

**Comment by NiedziolkaMichal** [comment]
@bsmth Done. I have also scanned through all changes and everything seems to be fine.

**Review by bsmth — APPROVED** [review]
Thanks @NiedziolkaMichal

**Comment by NiedziolkaMichal** [comment]
Thank you too

**Pull request merged**
