### PR TITLE
repeating-conic-gradient

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
Interactive Example for [repeating-conic-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-conic-gradient).

image

### CODE REVIEW

**Review by wbamberg — COMMENTED** [review]
Thanks for this PR, @NiedziolkaMichal !

I think interactive examples work best when there's a very clear connection between the code and the result. That's really the value that they provide. So for me they succeed when, by looking at the example, I can quickly grasp something about the syntax of the feature. I think this is much more important than the effect being impressive. That is, they're syntax examples, not demos.

In this case, although the effects are impressive, it's hard to understand the syntax and how it's producing the effect. This is especially the case since the MDN redesign, where we get so little width to show the code, so in a case like this really all we're seeing is the name of the property, we don't see the syntax at all.

I think in cases where the syntax is complex, like this, it's best to do two things to try to make it more comprehensible:
- have simpler examples. We have a whole page where we can go into all the detail we like.
- have fewer examples, and split them across multiple lines. This helps with readability and also with the width problem.

For example, here we could have just two examples, and just cover the basics, like:

Screen Shot 2022-05-11 at 12 27 33 PM

To me, although these are simpler effects, they're teaching me more about how the syntax on the left produces the output.

I don't think it necessarily has to be exactly this, but something like this.

What do you think?

**Comment by NiedziolkaMichal** [comment]
For sure examples written with proper indentation and line breaks, would improve readability. However change proposed here and in path function, contradicts style applied in pretty much every css example. Those are examples with very long property values: [background-image](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image), [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background), [border-image-source](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-source), [border-image](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image), [conic-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient), [linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient), [repeating-linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-linear-gradient), [radial-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/radial-gradient), [repeating-radial-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-radial-gradient), [shape-image-threshold](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-image-threshold), [basic-shape](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape). Line breaks usually occurs when another property is about to be set.

**Comment by wbamberg** [comment]
> For sure examples written with proper indentation and line breaks, would improve readability. However change proposed here and in path function, contradicts style applied in pretty much every css example. Those are examples with very long property values: [background-image](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image), [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background), [border-image-source](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-source), [border-image](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image), [conic-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient), [linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient), [repeating-linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-linear-gradient), [radial-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/radial-gradient), [repeating-radial-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-radial-gradient), [shape-image-threshold](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-image-threshold), [basic-shape](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape). Line breaks usually occurs when another property is about to be set.

Sorry, I know this is not consistent with our past practice. But I think in the cases you've listed here our past practice doesn't really serve our users well, and this has got worse since the redesign - examples that were marginally OK before are not any more.

**Comment by NiedziolkaMichal** [comment]
Alright, how about those 2 examples?
image

image

**Review by wbamberg — APPROVED** [review]
These look great to me. Thank you for your understanding @NiedziolkaMichal !

**Pull request merged**
