### PR TITLE
Add an example for `for`

### PR DESCRIPTION
**Pull request by MrBrain295**
#2374

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
Currently, this example doesn't show how attribute `for` is useful. You have also set its content to the value of attribute `id`, while `name` should be used instead. I think that the value of property `height` is currently invalid for this amount of content.

**Comment by MrBrain295** [comment]
@NiedziolkaMichal I have made the requested changes.

**Comment by NiedziolkaMichal** [comment]
@MrBrain295 Sorry but I don't think that you have. The value of attribute `for` is still pointing to `name` instead of `id` and the example doesn't show how this attribute is useful. You should also get rid of `form` element since we don't use it for similar examples.

**Comment by MrBrain295** [comment]
I’ve applied the feedback except for demonstrating it’s usefulness which I don’t know how I should do.

**Comment by NiedziolkaMichal** [comment]
It would be great if your CSS would have an immediate visual impact. Additionally, the attribute selector might be confusing to the user when the name of the attribute is `for`.
How about something like that?
image
When the reader will click on the labels, he/she might notice that label without the attribute `for` is not setting the focus state to the control field. Additionally, usage its usage in the `output` element is shown. This example should also have JS code though because `output` is supposed to be an interactive element.

**Comment by estelle** [comment]
i added your suggestions. Now we just need to add the JS file.

**Comment by queengooborg** [comment]
Thanks everyone -- because this has been sitting around for a while, I've decided to go ahead and make the requested changes.  This is now ready to go!

**Review by queengooborg — APPROVED** [review]

**Pull request merged**
