### PR TITLE
style: wire in and run stylelint with prettier

### PR DESCRIPTION
**Pull request by nschonni**
Was wondering how the malformed CSS wasn't blocked by CI from the other PR, and found that stylelint was a dependency, but not fully configured.
- Replace `prettier-stylelint` with maintained plugins
- Autofix issues with some manual updates and disables for the already configured issues
- Add call to CI

### CODE REVIEW

**Comment by nschonni** [comment]
Prettier fixing and style rule appears to be conflicting with itself for the leading zero

**Comment by NiedziolkaMichal** [comment]
I think it would be good to make `.stylelintrc` be the same as [.stylelintrc.json](https://github.com/mdn/yari/blob/main/.stylelintrc.json) in yari, except for the fact that it uses `stylelint-scss` plugin, while we use pure css here. I have checked the outcome and it looks satisfying. The unfortunate side effect is removal of alignment in few examples like this:

```css
.styled {
    background-image: linear-gradient(to top left,
                                      rgba(0, 0, 0, .2),
                                      rgba(0, 0, 0, .2) 30%,
                                      rgba(0, 0, 0, 0));
    box-shadow: inset 2px 2px 3px rgba(255, 255, 255, .6),
                inset -2px -2px 3px rgba(0, 0, 0, .6);
}
.styled:active {
    box-shadow: inset -2px -2px 3px rgba(255, 255, 255, .6),
                inset 2px 2px 3px rgba(0, 0, 0, .6);
}
```
After eslint:
```css
.styled {
    background-image: linear-gradient(to top left, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2) 30%, rgba(0, 0, 0, 0));
    box-shadow: inset 2px 2px 3px rgba(255, 255, 255, 0.6), inset -2px -2px 3px rgba(0, 0, 0, 0.6);
}

.styled:active {
    box-shadow: inset -2px -2px 3px rgba(255, 255, 255, 0.6), inset 2px 2px 3px rgba(0, 0, 0, 0.6);
}
```

Is there anything we could do about it?

**Review by schalkneethling — APPROVED** [review]
Hey @nschonni, thank you for adding this! This looks like a great addition and looks to be working well. @NiedziolkaMichal, if you are :+1: for this as well, please feel free to merge. Thanks! 🎉

**Comment by NiedziolkaMichal** [comment]
Alright, everything looks good. Thanks a lot @nschonni

**Pull request merged**
