### PR TITLE
Added All Tab-Sizes.

### PR DESCRIPTION
**Pull request by sahilempire**
Hello,

I have **added all the Tab-Sizes**.
**Please merge by pull-request**.

Thanks.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Hi @sahilempire !

I don't really understand what you are doing here. I gave you a very detailed review of this work in oyur other PR: https://github.com/mdn/interactive-examples/pull/1762

But then you closed that PR and opened up this one, which doesn't seem to have addressed any of my comments at all.

You need to go back and re-read my review.

Also, just in case you were not clear on this — you don't need to open a new PR to submit fixes. You can just push more changes to the same branch and it will update the existing PR.

**Comment by sahilempire** [comment]
hello @chrisdavidmills ,

I sincerely sorry for this, but I thought if I have to make changes, then i have to make a new pull request again, sorry, but  I am keep improving myself in Open Source World.

And I have correct my meta.json file, still getting this unknown error, and still unable to merge my codes.

Thanks.

**Comment by chrisdavidmills** [comment]
> hello @chrisdavidmills ,
> 
> I sincerely sorry for this, but I thought if I have to make changes, then i have to make a new pull request again, sorry, but I am keep improving myself in Open Source World.

No need to apologise — git can be very confusing at the best of times. This is a very easy mistake to make when you are just starting out with it.

> And I have correct my meta.json file, still getting this unknown error, and still unable to merge my codes.

The error is not unknown. I know exactly why the CI is failing, and I [wrote about it in your other PR](https://github.com/mdn/interactive-examples/pull/1762#issuecomment-777351832). Read my feedback carefully, and update your PR as appropriate.

**Comment by chrisdavidmills** [comment]
@sahilempire So, your latest change sems to have made the example more incorrect than it was before — the property is called `tab-size`, not `tabe-size`. As I've said a couple of times before, you need to go and read my comments on the other pull request carefully.

The short version is — an example for tab-size already exists at https://github.com/mdn/interactive-examples/tree/master/live-examples/css-examples/text, so what you need to do is delete your example and improve that one instead, as described in my previus comment.

**Comment by sahilempire** [comment]
Hi @chrisdavidmills ,

I have **done all changes as you told me**, and the happiness is **I'm not getting any error** or any conflict, and my codes **passed all Travis CI tests**.
But **my pull request haven't merged** yet. **Is their anything i forget to do?**

Thanks.

**Comment by chrisdavidmills** [comment]
@sahilempire first of all, I've got no idea why you keep writing the property name as `tabe-size`, when it is clearly `tab-size`.

Secondly, you've still not resolved this bit of my original comment:

"However, one thing does need updating on the existing example. As Will said on his original description — "Note that it's prefixed in Firefox, so the interactive example choices need to set both tab-size and -moz-tab-size."

So this means you need to update the choices to include both, e.g.

<pre><code class="language-css">-moz-tab-size: 4;
tab-size: 4;</code></pre>
"

**Review by sahilempire — COMMENTED** [review]
`tabe-size` to `tab-size`

**Review by sahilempire — COMMENTED** [review]
**Inserting** `-moz-tab-size` with `tab-size`

**Comment by sahilempire** [comment]
Hi @chrisdavidmills ,

I think this time I have done all things correctly, Please check this, and please merge this if okay.

Thank you.

**Review by chrisdavidmills — COMMENTED** [review]
Hi @sahilempire . This still isn't working properly. Did you actually test it locally before submitting this? I'm guessing not. You need to make sure that what you submit actually works before submitting a PR.

This has gone on long enough, so let's get it fixed up.

In `tab-size.css `, the rules you have included aren't going to do anything because there are no elements in the example to be selected by those selectors. So let's update it to this:

```
#example-element {
  border: 1px solid black;
}
```

As it is useful for seeing what effect `tab-size` is having.

In `tab-size.html`, there are a whole load of issues that I had to fix before it started working. The working code is as follows:

```
<section id="example-choice-list" class="example-choice-list large" data-property="tabSize">

    <div class="example-choice" initial-choice="true">
        <pre><code class="language-css">tab-size: 10px;
-moz-tab-size: 10px;</code></pre>
        <button type="button" class="copy hidden" aria-hidden="true">
            <span class="visually-hidden">Copy to Clipboard</span>
        </button>
    </div>

    <div class="example-choice">
        <pre><code class="language-css">tab-size: 16px;
-moz-tab-size: 16px;</code></pre>
        <button type="button" class="copy hidden" aria-hidden="true">
            <span class="visually-hidden">Copy to Clipboard</span>
        </button>
    </div>

    <div class="example-choice">
        <pre><code class="language-css">tab-size: 24px;
-moz-tab-size: 24px;</code></pre>
        <button type="button" class="copy hidden" aria-hidden="true">
            <span class="visually-hidden">Copy to Clipboard</span>
        </button>
    </div>

    <div class="example-choice">
        <pre><code class="language-css">tab-size: 4;
-moz-tab-size: 4;</code></pre>
        <button type="button" class="copy hidden" aria-hidden="true">
            <span class="visually-hidden">Copy to Clipboard</span>
        </button>
    </div>
</section>

<div id="output" class="output hidden">
    <section id="default-example">
      <pre id="example-element">	123</pre>
    </section>
</div>
```

Have a careful look and compare it to your code to see what is different. The biggest issues were:

1. The example choices not having the `example-choice`  class on them.
2. Everything having `initial-choice=true` set on it; only one choice should have this
3. The outer choice wrapper having `data-property="border-radius"` set on it, which should have been `data-property="tabSize"` to match the property name given to the example in `meta.json`
4. The actual example at the bottom of the file being completely deleted.
5. The CSS code having `<br>` tags put in it.

This is quite a lot to take in, so don't worry. I'll add the updates to the PR this time around. 

Thanks for your contribution.

**Pull request merged**
