### PR TITLE
Update CONTRIBUTING-CSS

### PR DESCRIPTION
**Pull request by bsmth**
This PR adds languages to code blocks, formatting fixes.

### CODE REVIEW

**Comment by NiedziolkaMichal** [comment]
I think it's better to keep &lt;section> elements in the single line. This page is was written to teach structure of the interactive example file, but also to allow contributors to easily copy-paste the entire fragment. All interactive examples have &lt;section> written without any line breaks, so guide should teach to do the same.

I am also not sure about this fragment:
```html
<section
    id="..."
    data-property="box-decoration-break -webkit-box-decoration-break"
></section>
```
This fragment is now larger and it's missing class attribute. I feel it's not worth to make it `html` type, for the sake of simplicity.

Overall you have done a great job. Could you do the same for other .md files?

**Comment by bsmth** [comment]
hi @NiedziolkaMichal let me have another look, there might be a better way to handle this.

>Could you do the same for other .md files?

I can indeed, I propose to follow up with a separate PR once we land this one, how does that sound?

**Comment by bsmth** [comment]
I've set the max line length to 120 for Prettier in https://github.com/mdn/interactive-examples/pull/2274/commits/5a1ba0cdd654f5ec40d8b79cc1abaec07bf8aba5 which seems to work better, what do you think?

**Comment by bsmth** [comment]
>I am also not sure about this fragment:

```html
<section
    id="..."
    data-property="box-decoration-break -webkit-box-decoration-break"
></section>
```

I see your point, we could revert this if you think readers will know where to put it:

```
data-property="box-decoration-break -webkit-box-decoration-break"
```

**Comment by bsmth** [comment]
@NiedziolkaMichal do you want to have another review?

**Comment by NiedziolkaMichal** [comment]
It looks good as it is, thank you for this PR.

**Comment by bsmth** [comment]
Thanks @NiedziolkaMichal

**Pull request merged**
