### PR TITLE
fix: Improve contrast of SVG element

### PR DESCRIPTION
**Pull request by onno-vdbroek**
### Description

Improve contrast of the SVG element's fill to the SVG element's border and page background for issue #2054 
### Motivation

The SVG element's fill didn't comply with the WCAG contrast criteria. By improving the contrast it now complies with the WCAG AA criteria for Graphical Objects and User Interface Components.

### CODE REVIEW

**Review by chrisdavidmills — COMMENTED** [review]
Hi there @onno-vdbroek!

I've had a look at this, and I don't really get the point of this change.

To clarify — this is the example at the top of https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events, correct?

When I test the original background fill versus the text color on https://webaim.org/resources/contrastchecker/, it passes the tests fine. When I test your modified background fill, it fails WGAC AAA for Normal Text.

Am I missing something here?

**Comment by onno-vdbroek** [comment]
Hello @chrisdavidmills!

Thank you for reviewing my pull request.

The example we're talking about is indeed https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events.

As mentioned in a comment on this issue (https://github.com/mdn/interactive-examples/issues/2054#issuecomment-1331308570) the example doesn't meet proper contrast guidelines in **dark theme**.  My modification is about the background fill of the SVG element **versus the dark theme page background (hex color #1b1b1b)**, not the text.

I found that the original background fill of the SVG element versus the dark theme page background didn't pass any WGAC tests. To comply with the contrast criteria I changed the SVG background fill to a lighter color so it passed the _WCAG AA test for Graphical Objects and User Interface Components._

You're right that my modified background fill fails with the _WGAC AAA for Normal Text_. But it still complies with the _WGAC **AA** for Normal Text_.

I think by changing the SVG background fill color we now have the best possible outcome: it complies with the _WGAC AA for Normal Text_  (by testing the SVG background fill versus the text) and it passes the _WCAG AA test for Graphical Objects and User Interface Components._ (by testing the SVG background fill versus the dark theme page background)

I hope I clarified the reason for my pull request. It was a bit tricky to find the right color that passes the most amount of tests (SVG background fill versus page background/versus SVG stroke/versus text).

This is my first pull request ever so I'm thankful for your help. If anything is still unclear I'm happy to try to explain it further.

**Comment by bsmth** [comment]
FYI I think this was already touched in https://github.com/mdn/interactive-examples/commit/f32a584cb847b5454270afc94d906de25080bedd#diff-f21bbc22811d892093185d1644b55edd90f715a2fa108e00c07735e8cc6d63fa, although this change does make some contrast improvements.

**Review by bsmth — APPROVED** [review]
I would leave a +1, curious what @chrisdavidmills thinks!

**Comment by onno-vdbroek** [comment]
Thanks for reviewing my change. Unfortunately, I didn't know this issue was already touched because when I made the change, the checkbox for this issue/fix wasn't checked. Although I hope my contribution was helpful. :)

**Comment by bsmth** [comment]
Sure thing, I think we can merge this. Thank you!

**Pull request merged**
