### PR TITLE
Add Promise.finally() example

### PR DESCRIPTION
**Pull request by georapbox**
Pull Request for issue #1653

### CODE REVIEW

**Review by mattiapontonio — CHANGES_REQUESTED** [review]
```JavaScript
let​ fetching;​
​fetch​(​'./')​
.​finally​(​function​ ​(​)​ ​{
 fetching​ ​=​ ​false​;​
 console.assert(fetching == false);
}​)​;​
fetching = true;
console.assert(fetching);
```
My version.
Please _merge_ if You want.

**Comment by peterbe** [comment]
@georapbox please ignore @_mattiapontonio feedback. He's not an officially reviewer on this repo.

**Comment by peterbe** [comment]
@georapbox Any chance you can merge in the latest upstream `master` branch and we'll try this again?

**Comment by georapbox** [comment]
@peterbe I've resolved conflicts and merged in the latest master.

**Comment by peterbe** [comment]
@wbamberg Are you the best person to review this?

**Comment by wbamberg** [comment]
It looks like https://github.com/mdn/interactive-examples/issues/1653 was already fixed by https://github.com/mdn/interactive-examples/pull/1835. Sorry @georapbox that this is just because your original PR didn't get reviewed in time.

**Comment by georapbox** [comment]
@wbamberg No worries!

**Pull request closed without merging**
