### PR TITLE
Update break-word

### PR DESCRIPTION
**Pull request by CShepartd**
Update break-word according to update https://developer.mozilla.org/en-US/docs/Web/CSS/word-break and specs https://drafts.csswg.org/css-text-3/#word-break-property

### CODE REVIEW

**Comment by schalkneethling** [comment]
@CShepartd Thank you for your contribution.

The current example content does not clearly show the difference when switching between say `normal` and `break-word`. To remedy this, I would suggest adding the following work at the end of this[1] sentence `Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu`

[1] https://github.com/mdn/interactive-examples/blob/master/live-examples/css-examples/word-break.html#L24

**Comment by CShepartd** [comment]
> The current example content does not clearly show the difference when switching between say normal and break-word.
Cuz FF/IE/Edge dont support it. Look in Chrome/Opera at exaple https://codepen.io/anon/pen/YYgEay
Or wait, look for "better demonstrate" at pic:
wbexample

**Comment by schalkneethling** [comment]
> Cuz FF/IE/Edge dont support it.
 I did test in Chrome. You will see what I mean if you do not have your browser sized as narrowly as your screenshots show above.

**Comment by CShepartd** [comment]
Ok, i get now and update example text to:
`Honorificabilitudinitatibus califragilisticexpialidocious Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu 次の単語グレートブリテンおよび北アイルランド連合王国で本当に大きな言葉`

**Comment by CShepartd** [comment]
Ok, i get now and updated example text

**Pull request merged**
