### PR TITLE
Adding an example for overscroll-behavior-y

### PR DESCRIPTION
**Pull request by meghannfh**
### Description

Added css example to demonstrate overscroll-behavior isolated to only the y-axis.

### Motivation

Example includes scrolling on both axis that allows the viewer to better visually compare scrolling behavior when it is isolated to just the y-axis.

### Additional details

There is not an existing example

### CODE REVIEW

**Comment by meghannfh** [comment]
@NiedziolkaMichal Just wondering if you might be able to give me some insight on this.
I noticed there was an issue with this PR. Is there any action required on my end? I noticed something regarding the css-lint.

**Review by NiedziolkaMichal — APPROVED** [review]
Everything looks great. Thanks for adding this example.

**Comment by NiedziolkaMichal** [comment]
@meghannfh Unfortunately, you need to sign your commits, so we are able to merge them with the main branch.
On how to do that, please check [GPG commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) and [Retroactively Sign Git Commits](https://webdevstudios.com/2020/05/26/retroactively-sign-git-commits/). Plenty of repositories require commits to be signed, so this is something you will need in the future anyway.

**Comment by meghannfh** [comment]
> @meghannfh Unfortunately, you need to sign your commits, so we are able to merge them with the main branch. On how to do that, please check [GPG commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) and [Retroactively Sign Git Commits](https://webdevstudios.com/2020/05/26/retroactively-sign-git-commits/). Plenty of repositories require commits to be signed, so this is something you will need in the future anyway.

Thanks for the info. I've just tried pushing a new commit with a GPG signature but for some reason I'm not seeing it reflected here or on my fork of the repo...
Screen Shot 2023-02-23 at 20 29 39

Or am I needing to somehow go back and sign all past commits?

**Comment by NiedziolkaMichal** [comment]
@bsmth Has lifted the GPG signing requirement, so we are good to go. Thank you for your contribution.

**Pull request merged**
