### PR TITLE
Updates to box-shadow and background-image

### PR DESCRIPTION
**Pull request by wbamberg**
This updates two examples:

* `box-shadow` to make the colors more interesting (in particular, the initial example originally had a quite subtle black shadow)

* `background-image` to show slightly different aspects of the property: (1) one image, (2) two images, (3) the same two images, in a different order, (4) a gradient and an image file

I should probably have made two separate PRs for this. Let me know if you need that. Also I'm happy to discuss whether these are in fact improvements :).

### CODE REVIEW

**Comment by wbamberg** [comment]
I tried making another change, to change the [linear-gradient definition](https://github.com/wbamberg/interactive-examples/blob/b8ff15be0b4a153a4fc81baafdff7dc40a1986e8/live-examples/css-examples/background-image.html#L27) from:

`linear-gradient(to top, rgba(255,255,0,0.5), rgba(0,0,255,0.5))`

to

`linear-gradient(rgba(0,0,255,0.5), rgba(255,255,0,0.5))`

...just to make that line shorter.

But when I try to commit, I'm getting this husky error:

` ERROR  There is no matching file for ./docs/css/css-examples-libs-1-8-4.css in /Users/Mozilla/git/wbamberg/interactive-examples `

Do you know what this means?

**Comment by schalkneethling** [comment]
> ERROR There is no matching file for ./docs/css/css-examples-libs-1-8-4.css in /Users/Mozilla/git/wbamberg/interactive-examples

> Do you know what this means?

@wbamberg Do you have the latest from master?

**Comment by wbamberg** [comment]
@schalkneethling , I think so:

```
$ git log --oneline
b8ff15b (HEAD -> css-example-updates, origin/css-example-updates) Make the prettiest one the initally selected choice
507b60b Updates to box-shadow and background-image
a4ceb99 (upstream/master, master) Merge pull request #332 from schalkneethling/adds-husky-for-pre-commit-hooks
60ac2cb Adds husky for precommit hooks
a7cf9cd Merge pull request #331 from schalkneethling/issue#330-add-hash-to-lib-file-names
```

It's weird, also, that it didn't complain about the first two commits, and master wasn't updated between the second successful commit and this one.

**Comment by schalkneethling** [comment]
> Do you know what this means?

Ok, I know why that happened. No worries I will fix it in a follow on PR

**Pull request merged**
