### PR TITLE
chore(deps)!: bump node from v18 to v20

### PR DESCRIPTION
**Pull request by caugner**
### Description

Bumps Node.js from v18 to v20.

### Motivation

Node.js v18 will no longer be maintained after April 2025.

### Related issues and pull requests

Part of https://github.com/mdn/mdn/issues/521.

### CODE REVIEW

**Comment by bsmth** [comment]
I have this diff after `npm i && npm run build && npm start` (in package-lock.json):

```diff
     "node_modules/@mdn/bob/watify/pkg": {
-      "dev": true
+      "name": "watify",
+      "version": "0.0.1",
+      "dev": true,
+      "license": "MIT"
     },
```

**Review by bsmth — APPROVED** [review]
LGTM, thank you!

**Review by pepelsbey — APPROVED** [review]
🚀

**Comment by caugner** [comment]
> I have this diff after `npm i && npm run build && npm start` (in package-lock.json):

Good catch, thank you, I must have run `npm ci`. Now fixed. 👍

**Pull request merged**
