### PR TITLE
Update HTML area element image

### LINKED ISSUE #2229: [media] Old MDN Logo in the Example for `<area>`
- MDN page: [`<area>`: The Image Map Area element - HTML | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area) ([source in mdn/content repo](https://github.com/mdn/content/blob/510836b0fff9fd7fef01eba7a74962eb06106cf7/files/en-us/web/html/element/area/index.md?plain=1#L22))
- Embed interactive example: [pages/tabbed/area.html](https://interactive-examples.mdn.mozilla.net/pages/tabbed/area.html) ([source](https://github.com/mdn/interactive-examples/blob/9f1562f6d449c93dc4aef03470c4f8502baaa2cc/live-examples/html-examples/image-and-multimedia/area.html#L24))

The image here use a variant of the old MDN Logo. Should we [update](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/) it, or leave it there as a memento?

### PR DESCRIPTION
**Pull request by NiedziolkaMichal**
Replaces image used in area element which contained old MDN logo, with something new:
mdn-info3
image

Fixes #2229

### CODE REVIEW

**Comment by bsmth** [comment]
Do we have info on the licensing of these images? What about the image [linked in the issue](https://github.com/mdn/interactive-examples/issues/2229#issuecomment-1339062526) instead?

**Comment by NiedziolkaMichal** [comment]
HTML & CSS was copied from [freepnglogos](https://www.freepnglogos.com/images/html5-logo-31819.html), JS was copied from [wikimedia](https://commons.wikimedia.org/wiki/File:Unofficial_JavaScript_logo_2.svg) under MIT and two images on the bottom are coming from [https://angular.io/presskit](https://angular.io/presskit) under CC BY 4.0. In such case, they can be used on MDN?

**Comment by bsmth** [comment]
Thanks @NiedziolkaMichal, please use the .png in the linked issue (or feel free to make a nicer-looking version 😄). In future, we will have a fixed set of assets that we will be able to use across all examples, until then, we are not going to include images with logos from external projects, even though most of these have permissive licenses.

**Comment by NiedziolkaMichal** [comment]
Sure, I will add it and update HTML later.

**Comment by bsmth** [comment]
> Sure, I will add it and update HTML later.

Thank you 🙌🏻

**Comment by NiedziolkaMichal** [comment]
@bsmth Done :)

**Comment by bsmth** [comment]
Thanks, taking a look 👀

**Review by bsmth — APPROVED** [review]
Looks good, thank you 🙌🏻

**Comment by NiedziolkaMichal** [comment]
Thank you for your review.

**Pull request merged**
