### PR TITLE
Fix: correct return type for function

### PR DESCRIPTION
**Pull request by MendyBerger**
### Description
Correct return type for function

### CODE REVIEW

**Review by NiedziolkaMichal — CHANGES_REQUESTED** [review]
This example, with or without your changes, produces the following exception:
image

**Comment by MendyBerger** [comment]
@NiedziolkaMichal should be fixed with https://github.com/mdn/bob/pull/1046

**Comment by NiedziolkaMichal** [comment]
You are right, the error is gone in the new BOB version. Is this the expected result?
image

**Comment by MendyBerger** [comment]
Yes

**Comment by NiedziolkaMichal** [comment]
Alright, so everything looks good. Thanks

**Review by NiedziolkaMichal — APPROVED** [review]

**Pull request merged**
