### PR TITLE
Add TA.p[@@iterator] example; consistent file names for @@iterator & supportedValuesOf

### PR DESCRIPTION
**Pull request by Josh-Cena**
### Description

These accompany my recent content refactors.

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
Thanks, Josh, lgtm 👍🏻

**Comment by Josh-Cena** [comment]
I do need someone to help merge this

**Comment by Josh-Cena** [comment]
@bsmth Are you going to merge it?

**Comment by bsmth** [comment]
> @bsmth Are you going to merge it?

whoops, yes let's merge 👍🏻

**Pull request merged**
