### PR TITLE
Adds the groundwork for puppeteer tests and on test for the js editor

### PR DESCRIPTION
**Pull request by schalkneethling**
Run: `npm install` to get new dependencies, then
Run: `npm run unit-tests`

Note to Self: Change `unit-tests` to just be `test` as this now runs unit and functional tests

### CODE REVIEW

**Comment by schalkneethling** [comment]
Need to figure out how to run these headless tests in Travis.

**Comment by wbamberg** [comment]
This looks amazing!

But I get an error:

```
$ npm run unit-tests

> interactive-examples@1.0.0 unit-tests /Users/Mozilla/git/people/schalkneethling/interactive-examples
> jest

/Users/Mozilla/git/people/schalkneethling/interactive-examples/node_modules/jest-environment-puppeteer/lib/global.js:49
async function setup() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Mozilla/git/people/schalkneethling/interactive-examples/node_modules/jest-environment-puppeteer/setup.js:1:80)

npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "unit-tests"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! interactive-examples@1.0.0 unit-tests: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the interactive-examples@1.0.0 unit-tests script 'jest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the interactive-examples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs interactive-examples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls interactive-examples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Mozilla/git/people/schalkneethling/interactive-examples/npm-debug.log
```

I've called `npm run install`.

**Comment by schalkneethling** [comment]
@wbamberg I believe your Nodejs version might be out of date. Which version are you running? I will also need to make this explicit in the package.json now.

**Comment by schalkneethling** [comment]
@wbamberg I totally agree. As soon as I have it working in CI, building out these tests is the next priority. I like the suggestion of getting expected output dynamically, we will just have to figure out how to get at that with code.

**Pull request merged**
